2024-04-28 14:19:25,004 root INFO Test execution started: perform_search
2024-04-28 14:19:25,005 root INFO Browser: edge
2024-04-28 14:19:25,009 root INFO Test started: test
2024-04-28 14:19:25,009 root INFO Navigate to: 'https://wikipedia.org'
2024-04-28 14:19:25,715 selenium.webdriver.remote.remote_connection DEBUG POST http://localhost:62576/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "MicrosoftEdge", "platformName": "windows"}}, "desiredCapabilities": {"browserName": "MicrosoftEdge", "version": "", "platform": "WINDOWS"}}
2024-04-28 14:19:25,716 urllib3.connectionpool DEBUG Starting new HTTP connection (1): localhost:62576
2024-04-28 14:19:30,777 urllib3.connectionpool DEBUG http://localhost:62576 "POST /session HTTP/1.1" 500 1551
2024-04-28 14:19:30,778 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2024-04-28 14:19:30,804 root ERROR Could not start edge driver using the path './drivers/edgedriver*'
verify that the edgedriver_path setting points to a valid webdriver executable.
2024-04-28 14:19:30,837 root INFO Traceback (most recent call last):
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 78, in validate_exec_path
    yield matched_executable_path
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 159, in open_browser
    driver = GolemEdgeDriver(executable_path=ex_path)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 122
Current browser version is 124.0.2478.19 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe


2024-04-28 14:19:30,850 root ERROR Exception: Could not start edge driver using the path './drivers/edgedriver*'
verify that the edgedriver_path setting points to a valid webdriver executable.
Traceback (most recent call last):
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 78, in validate_exec_path
    yield matched_executable_path
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 159, in open_browser
    driver = GolemEdgeDriver(executable_path=ex_path)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 122
Current browser version is 124.0.2478.19 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\test_runner\test_runner.py", line 257, in run_test_function
    f(execution.data)
  File "C:\Users\devad\PycharmProjects\golem\tutorial\projects\Akshy\tests\perform_search.py", line 7, in test
    navigate("https://wikipedia.org")
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\actions.py", line 1379, in navigate
    get_browser().get(url)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\actions.py", line 1097, in get_browser
    return browser.get_browser()
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 235, in get_browser
    open_browser()
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 159, in open_browser
    driver = GolemEdgeDriver(executable_path=ex_path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\devad\PycharmProjects\golem\venv\lib\site-packages\golem\browser.py", line 84, in validate_exec_path
    raise Exception(msg)
Exception: Could not start edge driver using the path './drivers/edgedriver*'
verify that the edgedriver_path setting points to a valid webdriver executable.
2024-04-28 14:19:32,940 root INFO Test Result: CODE ERROR
